### ISSUE TITLE
Leader死掉后其他node并不能自动选举其他的Leader

### ISSUE THREAD

**Issue by brightzheng100** [nananatsu/kvdb#2]
比如我在三个console分别跑，以便模拟三个node的集群。

```yaml
node:
  workDir: ./data
  name: node1
  peerAddress: localhost:3900
  serverAddress: localhost:8900
  servers: 
    node1: localhost:3900
    node2: localhost:3901
    node3: localhost:3902
```

```yaml
node:
  workDir: ./data
  name: node2
  peerAddress: localhost:3901
  serverAddress: localhost:8901
  servers: 
    node1: localhost:3900
    node2: localhost:3901
    node3: localhost:3902
```

```yaml
node:
  workDir: ./data
  name: node3
  peerAddress: localhost:3902
  serverAddress: localhost:8902
  servers: 
    node1: localhost:3900
    node2: localhost:3901
    node3: localhost:3902
```

假设node2获得选取后，适时ctl + c让其下线，但其他的node并不能选取出leader来。
是我的配置存在错误吗？
