### ISSUE TITLE
单个node无法自行选举Leader

### ISSUE THREAD

**Issue by brightzheng100** [nananatsu/kvdb#3]
假设我只有一个node，且配置如下：

```yaml
node:
  workDir: ./data
  name: node1
  peerAddress: localhost:3900
  serverAddress: localhost:8900
  servers: 
    node1: localhost:3900
```

启动后并不能自行选举成为leader -- 也就是说，单个node的集群无法正常运行？
